source 'https://rubygems.org'

gem 'geocoder', '~> 1.2.2'
gem 'rails', '4.1.1'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'sprint'
gem 'twilio-ruby', '~> 3.11'
gem 'whenever', '~> 0.9.2', :require => false
gem 'bitly', '~> 0.10.1'

group :development, :test do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails', '~> 4.2.1'
  gem 'jasmine'
  gem 'dotenv-rails'
end




group :test do
  gem 'timecop', '~> 0.7.1'
  gem 'faker', '~> 1.1.2'
  gem 'capybara', '~> 2.1.0'
  gem 'launchy', '~> 2.3.0'
  gem 'selenium-webdriver', '~> 2.39.0'
end