language: ruby
rvm:
  - "2.1.1"

#script: bundle exec rspec spec
#before_script:
#  - psql -c 'create database travelblog_test;' -U postgres

env:
  - DB=postgresql

before_script: 
  - psql -c 'create database giggidy_test' -U postgres

script: 
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

