development:
  adapter: postgresql
  encoding: unicode
  database: giggidy_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: giggidy_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: giggidy_production
  pool: 5
  host: localhost